#!/usr/bin/env bash
set -euo pipefail

PYTHON_BIN="${PYTHON_BIN:-python}"
RUN_SLUG="${RUN_SLUG:-nifty50_stable_policy_long_seed_check}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-/private/tmp/matplotlib-alpha-portfolio-rl}"

export ASSETS="${ASSETS:-[\"RELIANCE.NS\",\"HDFCBANK.NS\",\"ICICIBANK.NS\",\"INFY.NS\",\"TCS.NS\",\"BHARTIARTL.NS\",\"LT.NS\",\"ITC.NS\",\"SBIN.NS\",\"HINDUNILVR.NS\"]}"
export MARKET_FEATURE_TICKER="${MARKET_FEATURE_TICKER:-^NSEI}"
export BENCHMARK_TICKER="${BENCHMARK_TICKER:-^NSEI}"
export BENCHMARK_NAME="${BENCHMARK_NAME:-NIFTY 50}"

export DATA_CACHE_DIR="${DATA_CACHE_DIR:-data_cache/nifty50_smoke}"
export MODEL_DIR="${MODEL_DIR:-models/${RUN_SLUG}}"

export TRAIN_START_DATE="${TRAIN_START_DATE:-2010-01-01}"
export TRAIN_END_DATE="${TRAIN_END_DATE:-2023-12-31}"
export VALID_START_DATE="${VALID_START_DATE:-2024-01-01}"
export VALID_END_DATE="${VALID_END_DATE:-2024-12-31}"
export TEST_START_DATE="${TEST_START_DATE:-2025-01-01}"
export TEST_END_DATE="${TEST_END_DATE:-2026-05-27}"

export EPISODES="${EPISODES:-100}"
export EPISODE_LENGTH="${EPISODE_LENGTH:-650}"
export BATCH_SIZE="${BATCH_SIZE:-128}"
export BUFFER_SIZE="${BUFFER_SIZE:-1500}"
export IPM_PRETRAIN_EPOCHS="${IPM_PRETRAIN_EPOCHS:-50}"
export MIN_SAVE_EPISODE="${MIN_SAVE_EPISODE:-20}"
export EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-4}"
export VALIDATION_FREQ="${VALIDATION_FREQ:-10}"

export ABLATION="${ABLATION:-current_baseline}"
export USE_IPM="${USE_IPM:-true}"
export USE_ONLINE_IPM="${USE_ONLINE_IPM:-true}"
export USE_BCM="${USE_BCM:-true}"
export USE_DAM="${USE_DAM:-false}"
export USE_ARB="${USE_ARB:-false}"
export USE_SPARSE_NETWORK="${USE_SPARSE_NETWORK:-false}"
export USE_PRIORITIZED_REPLAY="${USE_PRIORITIZED_REPLAY:-true}"
export USE_TARGET_POLICY_EVAL="${USE_TARGET_POLICY_EVAL:-true}"
export STABLE_POLICY_SELECTION_VERSION="${STABLE_POLICY_SELECTION_VERSION:-1}"

export REBALANCE_FREQ="${REBALANCE_FREQ:-5}"
export TRADING_COST_BPS="${TRADING_COST_BPS:-5}"
export SLIPPAGE_BPS="${SLIPPAGE_BPS:-5}"
export SPREAD_BPS="${SPREAD_BPS:-2}"
export MARKET_IMPACT_BPS="${MARKET_IMPACT_BPS:-0}"
export MAX_CASH_WEIGHT="${MAX_CASH_WEIGHT:-0.05}"
export CASH_PENALTY="${CASH_PENALTY:-0.20}"
export DRAWDOWN_PENALTY="${DRAWDOWN_PENALTY:-1.0}"
export SELECTION_DRAWDOWN_WEIGHT="${SELECTION_DRAWDOWN_WEIGHT:-1.0}"

"${PYTHON_BIN}" -m evaluation.ensemble_dashboard
cp assets/ensemble_dashboard_metrics.csv "runs/${RUN_SLUG}_ensemble_metrics.csv"
