#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RUN_SLUG="${RUN_SLUG:-paper_control_smoke}"
export RUN_SEEDS="${RUN_SEEDS:-42}"
export PAPER_CONTROL_ABLATIONS="${PAPER_CONTROL_ABLATIONS:-paper_baseline paper_ipm_bcm}"
export PAPER_CONTROL_EPISODES="${PAPER_CONTROL_EPISODES:-20}"
export PAPER_CONTROL_EPISODE_LENGTH="${PAPER_CONTROL_EPISODE_LENGTH:-260}"
export PAPER_CONTROL_BATCH_SIZE="${PAPER_CONTROL_BATCH_SIZE:-64}"
export PAPER_CONTROL_BUFFER_SIZE="${PAPER_CONTROL_BUFFER_SIZE:-500}"
export PAPER_CONTROL_IPM_PRETRAIN_EPOCHS="${PAPER_CONTROL_IPM_PRETRAIN_EPOCHS:-10}"
export PAPER_CONTROL_GAN_EPOCHS="${PAPER_CONTROL_GAN_EPOCHS:-20}"
export PAPER_CONTROL_CHECKPOINT_FREQ="${PAPER_CONTROL_CHECKPOINT_FREQ:-5}"
export PAPER_CONTROL_VALIDATION_FREQ="${PAPER_CONTROL_VALIDATION_FREQ:-5}"
export PAPER_CONTROL_MIN_SAVE_EPISODE="${PAPER_CONTROL_MIN_SAVE_EPISODE:-5}"
export PAPER_CONTROL_EARLY_STOPPING_PATIENCE="${PAPER_CONTROL_EARLY_STOPPING_PATIENCE:-2}"

exec "${SCRIPT_DIR}/run_paper_control_matrix.sh"
