#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RUN_SLUG="${RUN_SLUG:-nifty50_active_overlay_long_seed_check}"
export MODEL_DIR="${MODEL_DIR:-models/${RUN_SLUG}}"

export TRAIN_START_DATE="${TRAIN_START_DATE:-2010-01-01}"
export TRAIN_END_DATE="${TRAIN_END_DATE:-2023-12-31}"
export VALID_START_DATE="${VALID_START_DATE:-2024-01-01}"
export VALID_END_DATE="${VALID_END_DATE:-2024-12-31}"
export TEST_START_DATE="${TEST_START_DATE:-2025-01-01}"
export TEST_END_DATE="${TEST_END_DATE:-2026-05-27}"

export USE_ACTIVE_OVERLAY="true"
export ACTIVE_OVERLAY_BASE_POLICY="${ACTIVE_OVERLAY_BASE_POLICY:-Equal Weight}"
export ACTIVE_OVERLAY_BASE_WEIGHT="${ACTIVE_OVERLAY_BASE_WEIGHT:-0.80}"
export ACTIVE_OVERLAY_TILT_WEIGHT="${ACTIVE_OVERLAY_TILT_WEIGHT:-0.20}"
export ACTIVE_OVERLAY_TRACKING_PENALTY="${ACTIVE_OVERLAY_TRACKING_PENALTY:-0.05}"

export USE_TARGET_POLICY_EVAL="true"
export STABLE_POLICY_SELECTION_VERSION="1"

exec "${SCRIPT_DIR}/run_nifty50_baseline_cash_long_seed_check.sh"
